============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/mochi/projects/term1/python/oop
collected 3 items

test_calculator.py FF.                                                   [100%]

=================================== FAILURES ===================================
________________________________ test_positive _________________________________

    def test_positive():
            assert square(2) == 4
>           assert square(3) == 9
E           assert 6 == 9
E            +  where 6 = square(3)

test_calculator.py:6: AssertionError
________________________________ test_negative _________________________________

    def test_negative():
>           assert square(-2) == 4
E           assert -4 == 4
E            +  where -4 = square(-2)

test_calculator.py:9: AssertionError
=========================== short test summary info ============================
FAILED test_calculator.py::test_positive - assert 6 == 9
FAILED test_calculator.py::test_negative - assert -4 == 4
========================= 2 failed, 1 passed in 0.01s ==========================
